spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: group-service
  data:
    mongodb:
      uri: mongodb://heroku_d2m2vpbp:ntiopg20uohrv9f958gfbaiash@ds255784.mlab.com:55784/heroku_d2m2vpbp

server:
  port: 8366

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8360/eureka/
  instance:
    hostname: localhost